name: myenv
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - contourpy=1.3.1=py310h214f63a_0
  - cycler=0.12.1=py310haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py310h02ab6af_0
  - freetype=2.14.1=hfbffc0b_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=12.3.0=h3ef6528_1
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.9=py310h03f52e7_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.22.1=hb237eb7_0
  - libpng=1.6.54=ha15c746_0
  - libpq=17.6=h64815fc_1
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.8=py310haa95532_0
  - matplotlib-base=3.10.8=py310h26e45b9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=2.1.1=py310h300f80d_0
  - mkl_random=1.3.0=py310ha5e6156_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - numexpr=2.14.1=py310h7660c64_0
  - numpy=2.2.5=py310h7894be3_2
  - numpy-base=2.2.5=py310h7794460_2
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py310h096bfcc_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - pyparsing=3.2.5=py310haa95532_0
  - pyqt=6.9.1=py310h12ec796_0
  - pyqt6-sip=13.10.2=py310h630b2a1_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py310haa95532_0
  - qtbase=6.9.2=h3266e9d_6
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - setuptools=80.10.2=py310haa95532_0
  - sip=6.12.0=py310h706e071_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tomli=2.4.0=py310haa95532_0
  - tornado=6.5.4=py310h02ab6af_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\slsun\anaconda3\envs\myenv
